<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2020.1.0" />
        <PackageReference Include="RavenDB.Client" Version="7.0.2" />
        <PackageReference Include="SimpleInjector" Version="4.0.8" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BusinessEntities\BusinessEntities.csproj" />
        <ProjectReference Include="..\Data\Data.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="System.Configuration">
        <HintPath>..\..\..\..\..\..\..\..\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Configuration.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
